version: 0.2

env:
  variables:
    IMAGE_TAG: latest

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 726032358740.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Building React frontend image...
      - docker build -t react-frontend .
      - docker tag react-frontend:latest $REPO_URI:$IMAGE_TAG

  post_build:
    commands:
      - echo Pushing image...
      - docker push $REPO_URI:$IMAGE_TAG
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"frontend","imageUri":"%s"}]' $REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
